#!/bin/bash
#SBATCH --job-name=hello
#SBATCH --output=hello.%j.out
#SBATCH --time=00:01:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=a100
#SBATCH --qos=qos_gpu
#SBATCH --account=coses1_gpu
#SBATCH --gres=gpu:1

module load cuda/12.6.1
nvidia-smi
lspci | grep -i nvidia
echo "Hello from $(hostname)!"
conda run -n matbench python main.py
